### ISSUE TITLE
Bug: Visualisaatio 1 monthly datassa ylimääräinen selite

### ISSUE THREAD

**Issue by esalminen** [TVTKMO22-WP-GROUP-5/CarbonCruncher#22]
![Image](https://user-images.githubusercontent.com/49938344/233517518-4a9797b0-a3d5-40da-ac9e-4f97e158979a.png)

**Comment by anssikulotie** [comment]
Bug fixed:
![image](https://user-images.githubusercontent.com/112494975/233686801-66d18d59-3188-4f97-873c-698012463661.png)
