### ISSUE TITLE
Bug: Carbon cruncherin sivuilla näkyy selaimen konsolissa ( painamalla F12 pääsee konsoliin) Visu1 liittyvä virhe

### ISSUE THREAD

**Issue by esalminen** [TVTKMO22-WP-GROUP-5/CarbonCruncher#25]
![Image](https://user-images.githubusercontent.com/49938344/233521101-97242b30-3419-4def-965c-e8eb2cf9fd93.png)

**Comment by esalminen** [comment]
Estää testausta. Korjattava ASAP

**Comment by anssikulotie** [comment]
Bug fixed
![image](https://user-images.githubusercontent.com/112494975/233686682-e8f0a7fc-2c30-4993-83f5-589b7c3f7107.png)
